version: '3.4'

services:
  elasticsearch.api:
    container_name: api
    image: ${DOCKER_REGISTRY-}elasticsearchapi
    build:
      context: .
      dockerfile: Elasticsearch.API/Dockerfile

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0
    container_name: es01

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0
    container_name: es02
  
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.3.0
    container_name: kibana

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  kibanadata:
    driver: local

networks:
  esnet: